# Don't care about single/double quotes inside interpolation
Style/StringLiteralsInInterpolation:
  Enabled: false

# No braces around parameters doesn't work very nicely in this
# project because there are lots of hashes with string keys.
Style/BracesAroundHashParameters:
  Enabled: false

# TODO: refactor tests that don't conform to this cop.
Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'test/**/*'

# This cop doesn't work nicely with the style in the tests.
Style/ClosingParenthesisIndentation:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Performance/StringReplacement:
  Exclude:
    - 'lib/health_check/check_file_parser.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/AlignArray:
  Exclude:
    - 'test/unit/query_components/best_bets_test.rb'
    - 'test/unit/result_presenter_test.rb'

# Offense count: 2
Style/ClassVars:
  Exclude:
    - 'app.rb'
    - 'lib/unified_search/suggestion_blacklist.rb'

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/ExtraSpacing:
  Exclude:
    - 'lib/elasticsearch/base_worker.rb'
    - 'lib/elasticsearch/index.rb'
    - 'lib/elasticsearch/scroll_enumerator.rb'
    - 'lib/search_parameters.rb'
    - 'test/integration/sitemap_test.rb'
    - 'test/integration_test_helper.rb'
    - 'test/unit/elasticsearch/elasticsearch_escaping_test.rb'
    - 'test/unit/facet_option_test.rb'

# Offense count: 40
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/MethodCallParentheses:
  Exclude:
    - 'lib/best_bets_checker.rb'
    - 'test/unit/base_registry_test.rb'
    - 'test/unit/elasticsearch/elasticsearch_index_advanced_search_test.rb'
    - 'test/unit/sitemap/sitemap_index_test.rb'

# Offense count: 2
Style/MethodCalledOnDoEndBlock:
  Exclude:
    - 'lib/elasticsearch/advanced_search_query_builder.rb'
    - 'lib/taxonomy_prototype/data_parser.rb'

# Offense count: 4
Style/MultilineBlockChain:
  Exclude:
    - 'lib/document.rb'
    - 'lib/parameter_parser/search_parameter_parser.rb'
    - 'lib/schema/document_types.rb'
    - 'lib/schema/index_schema.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/MultilineBlockLayout:
  Exclude:
    - 'lib/indexer/bulk_payload_generator.rb'

# Offense count: 6
Style/StructInheritance:
  Exclude:
    - 'lib/health_check/basic_auth_credentials.rb'
    - 'lib/health_check/search_check.rb'
    - 'lib/registries.rb'
    - 'lib/unified_search/spell_check_fetcher.rb'
    - 'lib/unified_search/spell_check_presenter.rb'
    - 'lib/unified_search/suggestion_blacklist.rb'
