inherit_gem:
  rubocop-govuk:
    - config/default.yml

Style/ConditionalAssignment:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*.rake'
    - 'spec/**/*'

# No braces around parameters doesn't work very nicely in this
# project because there are lots of hashes with string keys.
Style/BracesAroundHashParameters:
  Enabled: false

# The class vars in these two files are acceptable because
# they aren't inherited.
Style/ClassVars:
  Exclude:
    - 'app.rb'
    - 'lib/search/suggestion_blocklist.rb'

# Cannot use %i arrays as rake task arguments
Style/SymbolArray:
  Exclude:
    - 'lib/tasks/*.rake'

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - 'spec/**/*'
