Style/ConditionalAssignment:
  Enabled: false

Performance/TimesMap:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*.rake'
    - 'spec/**/*'

# Don't care about single/double quotes inside interpolation
Style/StringLiteralsInInterpolation:
  Enabled: false

# No braces around parameters doesn't work very nicely in this
# project because there are lots of hashes with string keys.
Style/BracesAroundHashParameters:
  Enabled: false

# This cop doesn't make things clearer in a lot of cases. Using the modifier
# should be up to the developer.
Style/IfUnlessModifier:
  Enabled: false

# The class vars in these two files are acceptable because
# they aren't inherited.
Style/ClassVars:
  Exclude:
    - 'app.rb'
    - 'lib/search/suggestion_blacklist.rb'

# Cannot use %i arrays as rake task arguments
Style/SymbolArray:
  Exclude:
    - 'lib/tasks/*.rake'

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - 'spec/**/*'
