migrated:
# Collections Publisher
- mainstream_browse_page
- specialist_sector # topic format is mapped to specialist_sector in Rummager.
# Contacts
- contact
# Publisher
- answer
- guide
- help_page
- licence
- local_transaction
- place
- transaction
- simple_smart_answer
# Specialist Publisher
- aaib_report
- asylum_support_decision
- business_finance_support_scheme
- cma_case
- countryside_stewardship_grant
- dfid_research_output
- drug_safety_update
- employment_appeal_tribunal_decision
- employment_tribunal_decision
- european_structural_investment_fund # use Rummager name as mapping occurs before validation check
- international_development_fund
- maib_report
- medical_safety_alert
- raib_report
- residential_property_tribunal_decision
- service_standard_report
- tax_tribunal_decision
- utaac_decision
# Other
- calendar
- finder # Specialist Publisher and Whitehall
- hmrc_manual
- hmrc_manual_section
- manual
- manual_section
- policy
- recommended-link # Search admin
- service_manual_guide
- service_manual_homepage
- service_manual_service_standard
- service_manual_topic
- task_list
- travel_advice
- travel_advice_index
- special_route:
  - '/help'
  - '/find-local-council'

indexable: []

non_indexable:
- calculator
- license_finder
- smart_answer # this is the format for the `/<path>/y` flow landing page for smart answers
- special_route:
  - '/homepage'
  - '/tour'
  - '/help/ab-testing'
  - '/help.json'
  - '/random'
  # from whitehall
  - "/BingSiteAuth.xml"
  - "/api"
  - "/apple-touch-icon-114x114.png"
  - "/apple-touch-icon-144x144.png"
  - "/apple-touch-icon-57x57.png"
  - "/apple-touch-icon-72x72.png"
  - "/apple-touch-icon-precomposed.png"
  - "/apple-touch-icon.png"
  - "/contact"
  - "/courts-tribunals"
  - "/email-signup"
  - "/email-signup/confirm"
  - "/email/subscriptions"
  - "/email/unsubscribe"
  - "/favicon.ico"
  - "/google6db9c061ce178960.html"
  - "/google991dec8b62e37cfb.html"
  - "/googlef35857dca8b812e7.html"
  - "/government"
  - "/government/get-involved"
  - "/government/history"
  - "/government/history/1-horse-guards-road"
  - "/government/history/10-downing-street"
  - "/government/history/11-downing-street"
  - "/government/history/king-charles-street"
  - "/government/history/lancaster-house"
  - "/government/how-government-works"
  - "/humans.txt"
  - "/info"
  - "/lloyds-share-offer-further-details"
  - "/lloydsfactsheet"
  - "/performance"
  - "/performance/big-screen"
  - "/robots.txt"
  - "/search.json"
  - "/search/opensearch.xml"
  - "/sitemap.xml"
  - "/sitemaps"
  - "/tour"
  - "/ukwelcomes"

# detailed formats
- detailed_guide
# whitehall formats
- about
- about_our_services
- access_and_opening
- authored_article
- case_study
- complaints_procedure
- consultation
#- contact # migrated
- corporate_report
- correspondence
- decision
- document_collection
- equality_and_diversity
- fatality_notice
- field_of_operation
#- finder # migrated
- foi_release
- form
- government_response
- guidance
- html_publication
- impact_assessment
- imported
- independent_report
- international_treaty
- map
- media_enquiries
- membership
- ministerial_role
- national_statistics
- national_statistics_announcement
- news_story
- notice
- official_statistics
- official_statistics_announcement
- oral_statement
- organisation
- our_energy_use
- our_governance
- person
- personal_information_charter
- petitions_and_campaigns
- policy_area
- policy_paper
- press_release
- procurement
- promotional
- publication
- publication_scheme
- recruitment
- regulation
- research
- services_and_information
- social_media_use
- speech
- staff_update
- statistical_data_set
- statistics
- statutory_guidance
- take_part
- terms_of_reference
- topical_event
- topical_event_about_page
- transparency
- welsh_language_scheme
- working_group
- world_location
- world_news_story
- worldwide_organisation
- written_statement
