migrated:
# Collections Publisher
- mainstream_browse_page
- specialist_sector # topic format is mapped to specialist_sector in Rummager.
# Contacts
- contact
# Publisher
- answer
- guide
- help_page
- licence
- local_transaction
- place
- transaction
- simple_smart_answer
# Specialist Publisher
- aaib_report
- asylum_support_decision
- business_finance_support_scheme
- cma_case
- countryside_stewardship_grant
- dfid_research_output
- drug_safety_update
- employment_appeal_tribunal_decision
- employment_tribunal_decision
- european_structural_investment_fund # use Rummager name as mapping occurs before validation check
- international_development_fund
- maib_report
- medical_safety_alert
- raib_report
- service_standard_report
- tax_tribunal_decision
- utaac_decision
# Other
- calendar
- finder # Specialist Publisher and Whitehall
- hmrc_manual
- hmrc_manual_section
- manual
- manual_section
- policy
- service_manual_guide
- service_manual_homepage
- service_manual_service_standard
- service_manual_topic
- task_list
- travel_advice
- travel_advice_index

indexable:
- smart-answer # transaction document type from the smart-answers publishing app
