migrated:
# Collections Publisher
- mainstream_browse_page
- specialist_sector # topic format is mapped to specialist_sector in Rummager.
# Contacts
- contact
# Publisher
- answer
- guide
- help_page
- licence
- local_transaction
- place
- transaction
- simple_smart_answer
# Specialist Publisher
- aaib_report
- asylum_support_decision
- business_finance_support_scheme
- cma_case
- countryside_stewardship_grant
- dfid_research_output
- drug_safety_update
- employment_appeal_tribunal_decision
- employment_tribunal_decision
- european_structural_investment_fund # use Rummager name as mapping occurs before validation check
- international_development_fund
- maib_report
- medical_safety_alert
- raib_report
- service_standard_report
- tax_tribunal_decision
- utaac_decision
# Other
- calendar
- finder # Specialist Publisher and Whitehall
- hmrc_manual
- hmrc_manual_section
- manual
- manual_section
- policy
- service_manual_guide
- service_manual_homepage
- service_manual_service_standard
- service_manual_topic
- smart-answer # needed to stop these rendering from mainstream. THis can be removed once we stop using mainstream.
- task_list
- travel_advice
- travel_advice_index

indexable:
- special_route:
  - '/help'
  - '/find-local-council'

non_indexable:
- calculator
- license_finder
- smart_answer # this is the format for the `/<path>/y` flow landing page for smart answers
- special_route:
  - '/homepage'
  - '/tour'
  - '/help/ab-testing'
  - '/help.json'
  - '/random'
# detailed formats
- detailed_guide
# whitehall formats
- about
- about_our_services
- access_and_opening
- authored_article
- case_study
- complaints_procedure
- consultation
#- contact # migrated
- corporate_report
- correspondence
- decision
- document_collection
- equality_and_diversity
- fatality_notice
- field_of_operation
#- finder # migrated
- foi_release
- form
- government_response
- guidance
- html_publication
- impact_assessment
- imported
- independent_report
- international_treaty
- map
- media_enquiries
- membership
- ministerial_role
- national_statistics
- national_statistics_announcement
- news_story
- notice
- official_statistics
- official_statistics_announcement
- oral_statement
- organisation
- our_energy_use
- our_governance
- person
- personal_information_charter
- petitions_and_campaigns
- policy_area
- policy_paper
- press_release
- procurement
- promotional
- publication
- publication_scheme
- recruitment
- regulation
- research
- services_and_information
- social_media_use
- speech
- staff_update
- statistical_data_set
- statistics
- statutory_guidance
- take_part
- terms_of_reference
- topical_event
- topical_event_about_page
- transparency
- welsh_language_scheme
- working_group
- world_location
- world_news_story
- worldwide_organisation
- written_statement
