---
base_path: "/find-brexit-guidance/email-signup"
content_id: 631a000b-dcfa-4cb9-a608-776f78142c6c
document_type: finder_email_signup
locale: en
publishing_app: search-api
rendering_app: finder-frontend
schema_name: finder_email_signup
title: Find Brexit guidance
description: Sign up for email alerts to Brexit guidance.
details:
  email_filter_by: facet_values
  email_filter_facets:
  - facet_id: business_activity
    facet_name: Organisation activity
    facet_choices:
    - key: product-or-goods
      content_id: d2f4d296-bc2f-4e97-aad8-ebb45637ebca
      radio_button_name: Product or goods
      topic_name: Product or goods
      prechecked: false
  subscription_list_title_prefix: 'Find Brexit guidance'
routes:
- path: "/find-brexit-guidance/email-signup"
  type: exact
