---
base_path: "/search/research-and-statistics/email-signup"
content_id: 119db584-0ae7-45e4-8f3a-fd79316c6921
document_type: finder_email_signup
locale: en
publishing_app: search-api
rendering_app: finder-frontend
schema_name: finder_email_signup
title: Research and statistics
description: You'll get an email every time research and statistics are updated, published or cancelled.
details:
  email_filter_by:
  email_filter_name:
  subscription_list_title_prefix: Statistics
  filter:
    content_purpose_supergroup: research_and_statistics
  email_filter_facets:
  - facet_id: content_store_document_type
    facet_name: document_type
  - facet_id: organisations
    facet_name: organisations
  - facet_id: world_locations
    facet_name: world locations
  - facet_id: topic
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: level_one_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
  - facet_id: level_two_taxon
    filter_key: all_part_of_taxonomy_tree
    facet_name: topics
routes:
- path: "/search/research-and-statistics/email-signup"
  type: exact
