---
base_path: "/find-eu-exit-guidance-business/email-signup"
content_id: 2818d67a-029a-4899-a438-a543d5c6a20d
document_type: finder_email_signup
locale: en
publishing_app: search-api
rendering_app: finder-frontend
schema_name: finder_email_signup
title: Find EU Exit guidance for your business
description: You'll get an email each time EU Exit guidance is published.
details:
  email_filter_by: facet_groups
  email_filter_name: facet_groups
  combine_mode: or
  email_signup_choice:
  - key: "52435175-82ed-4a04-adef-74c0199d0f46"
    radio_button_name: "52435175-82ed-4a04-adef-74c0199d0f46"
    topic_name: "appear in find eu exit guidance business finder"
    prechecked: true
  subscription_list_title_prefix: 'Find EU Exit guidance for your business'
routes:
- path: "/find-eu-exit-guidance-business/email-signup"
  type: exact
