---
tag: search-api.publishing.service.gov.uk
:concurrency: 5
staging:
  :concurrency:  20
production:
  :concurrency:  20
:require: ./lib/rummager.rb
:logfile: ./log/sidekiq.log
:queues:
  - default
  - bulk
:limits:
  bulk: 4
  default: 16
